title: The Simple Setup
description: Set things up simply
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

author:
  name: Liam Sreya

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      comments: true

search: true