title: Your Site Title
description: A minimal mistakes Jekyll site
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

# Optional extras
author:
  name: Your Name

# Enable caching for GitHub Pages
defaults:
  -
    scope:
      path: ""
    values:
      layout: archive