title: The Simple Setup
description: Set things up simply
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

# Optional extras
author:
  name: Liam Sreya

# Enable caching for GitHub Pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      comments: true

search: true